// 返回上一级
    function returnToParent() {
        if(window.history.length > 1) {
            window.history.back();
        } else {
            console.log('Return to Desktop via Bridge');
        }
    }

    // ================= 数据库配置 =================
    const db = window.MiniDB.databases.contacts;
    
    // 初始化 MasksDB 用于读取 USER
    const masksDb = window.MiniDB.databases.masks;

    let currentListType = 'CHAR'; 
    let currentEditId = null;
    let autoGeneratedAccount = '';
    let currentNetworkEntity = null;
    let contactSavePending = false;
    let contactImportPending = false;
    let activeDropdownList = null;
    let dropdownToggleLockUntil = 0;
    const relationTypeLabelMap = Object.freeze({
        Family: '家人',
        Partner: '恋人',
        Friend: '朋友',
        Colleague: '同事',
        家人: '家人',
        恋人: '恋人',
        朋友: '朋友',
        同事: '同事'
    });

    function normalizeRelationType(value) {
        const text = String(value == null ? '' : value).trim();
        if (!text || text === 'CUSTOM') return text;
        return relationTypeLabelMap[text] || text;
    }

    function getRelationTypeDisplayLabel(value) {
        return normalizeRelationType(value) || '未知';
    }

    function normalizeWorldbookAssocToken(value) {
        return String(value == null ? '' : value).trim();
    }

    function parseWorldbookAssocValues(value) {
        const raw = String(value == null ? '' : value).trim();
        if (!raw || /^none$/i.test(raw)) return [];
        return [...new Set(
            raw
                .split(/[|,\n]/)
                .map((item) => normalizeWorldbookAssocToken(item))
                .filter((item) => item && !/^none$/i.test(item) && /^worldbook:/i.test(item))
        )];
    }

    function serializeWorldbookAssocValues(values) {
        const normalized = [...new Set((Array.isArray(values) ? values : [])
            .map((item) => normalizeWorldbookAssocToken(item))
            .filter((item) => item && /^worldbook:/i.test(item)))];
        return normalized.length ? normalized.join('|') : 'NONE';
    }

    function mergeWorldbookAssocValues(currentValue, incomingValue) {
        return serializeWorldbookAssocValues([
            ...parseWorldbookAssocValues(currentValue),
            ...parseWorldbookAssocValues(incomingValue)
        ]);
    }

    function syncRelationTypeTabLabels() {
        const labels = ['家人', '恋人', '朋友', '同事', '填写'];
        document.querySelectorAll('#relation-modal .tab-btn').forEach((btn, index) => {
            if (labels[index]) btn.textContent = labels[index];
        });
        const relTypeInput = document.getElementById('inp-rel-type');
        if (relTypeInput && relTypeInput.value !== 'CUSTOM') {
            relTypeInput.value = normalizeRelationType(relTypeInput.value) || '家人';
        }
    }

    function resolveContactAssocLabel(type, value) {
        const raw = String(value == null ? '' : value).trim();
        if (!raw || /^none$/i.test(raw)) return 'None';
        const optionsState = window.__miniContactAssocOptions || {};
        const options = Array.isArray(optionsState[type]) ? optionsState[type] : [];
        if (type === 'worldbook') {
            const labels = parseWorldbookAssocValues(raw)
                .map((item) => {
                    const match = options.find((option) => option && option.value === item);
                    return match && match.label ? match.label : item.replace(/^worldbook:/i, 'Group ');
                })
                .filter(Boolean);
            if (!labels.length) return 'None';
            if (labels.length === 1) return labels[0];
            if (labels.length === 2) return labels.join(' / ');
            return `${labels.slice(0, 2).join(' / ')} +${labels.length - 2}`;
        }
        const match = options.find((item) => item && item.value === raw);
        if (match && match.label) return match.label;
        const legacyMap = type === 'preset'
            ? { MAIN_CHAR: 'Main Character', SIDE_KICK: 'Side Kick', VILLAIN: 'Villain' }
            : { GLOBAL_RULE: 'Global Rules', CITY_LORE: 'City Lore' };
        return legacyMap[raw] || raw;
    }

    function buildImportedContactFromCharacterData(dataNode, avatarBase64 = '') {
        const source = dataNode && typeof dataNode === 'object' ? dataNode : {};
        return {
            ...source,
            type: source.type || currentListType,
            nickname: source.nickname || source.name || 'Unknown',
            name: source.name || source.nickname || '',
            gender: source.gender || 'X',
            account: source.account || generateUniqueAccount(),
            language: source.language || '中文 (Mandarin)',
            signature: source.signature || source.creator_notes || source.personality || '',
            lore: source.lore || source.description || '',
            presetAssoc: source.presetAssoc || 'NONE',
            worldbookAssoc: serializeWorldbookAssocValues(
                Array.isArray(source.worldbookAssoc)
                    ? source.worldbookAssoc
                    : parseWorldbookAssocValues(source.worldbookAssoc)
            ),
            avatar: source.avatar || avatarBase64 || ''
        };
    }

    function collectCurrentContactFormData() {
        return {
            type: currentListType,
            nickname: document.getElementById('inp-nickname').value.trim(),
            name: document.getElementById('inp-name').value.trim(),
            gender: document.getElementById('inp-gender').value,
            account: autoGeneratedAccount,
            language: document.getElementById('inp-language').value,
            signature: document.getElementById('inp-sign').value.trim(),
            lore: document.getElementById('inp-lore').value.trim(),
            presetAssoc: document.getElementById('inp-preset').value,
            worldbookAssoc: serializeWorldbookAssocValues(parseWorldbookAssocValues(document.getElementById('inp-worldbook').value)),
            avatar: document.getElementById('val-avatar').value
        };
    }

    async function buildExportableContactData() {
        const contact = collectCurrentContactFormData();
        if (!currentEditId) return { ...contact, relations: [] };
        const storedContact = await db.contacts.get(currentEditId);
        const globalId = `${(storedContact && storedContact.type) || currentListType}_${currentEditId}`;
        const allRelations = await db.relations.toArray();
        return {
            ...(storedContact || {}),
            ...contact,
            id: currentEditId,
            relations: allRelations.filter((relation) => relation.sourceGlobalId === globalId || relation.targetGlobalId === globalId)
        };
    }

    function getDropdownNow() {
        return (window.performance && typeof window.performance.now === 'function')
            ? window.performance.now()
            : Date.now();
    }

    function lockDropdownToggle(duration = 80) {
        dropdownToggleLockUntil = getDropdownNow() + Math.max(0, Number(duration) || 0);
    }

    function isDropdownToggleLocked() {
        return getDropdownNow() < dropdownToggleLockUntil;
    }

    function normalizeContactIdentityText(value) {
        return String(value == null ? '' : value)
            .replace(/\r/g, ' ')
            .replace(/\s+/g, ' ')
            .trim()
            .toLowerCase();
    }

    function isAutoGeneratedAccount(value) {
        return /^[CN]_[A-Z0-9]+_[A-Z0-9]{4}$/i.test(String(value || '').trim());
    }

    function buildContactDuplicateFingerprint(contact) {
        if (!contact || typeof contact !== 'object') return '';
        const type = normalizeContactIdentityText(contact.type) || 'char';
        const account = normalizeContactIdentityText(contact.account);
        if (account && !isAutoGeneratedAccount(account)) return `account:${type}:${account}`;

        const nickname = normalizeContactIdentityText(contact.nickname);
        const name = normalizeContactIdentityText(contact.name);
        const signature = normalizeContactIdentityText(contact.signature);
        const lore = normalizeContactIdentityText(contact.lore);
        const avatar = String(contact.avatar || '').trim();
        const identity = [nickname, name].filter(Boolean).join('|');
        const narrative = [signature, lore].filter(Boolean).join('|');

        if (!identity) return '';
        if (narrative && narrative.length >= 16) return `story:${type}:${identity}:${narrative}`;
        if (avatar && narrative) return `portrait:${type}:${identity}:${narrative}:${avatar.slice(0, 96)}`;
        if (avatar && nickname && name) return `portrait:${type}:${nickname}|${name}:${avatar.slice(0, 96)}`;
        return '';
    }

    function pickPreferredContactValue(currentValue, incomingValue, options = {}) {
        const currentText = String(currentValue == null ? '' : currentValue).trim();
        const incomingText = String(incomingValue == null ? '' : incomingValue).trim();
        if (!incomingText) return currentText;
        if (!currentText) return incomingText;
        if (options.preferIncomingWhenLonger && incomingText.length > currentText.length + 8) return incomingText;
        return currentText;
    }

    function buildMergedContactChanges(existing, incoming) {
        if (!existing || !incoming) return {};
        const next = {
            nickname: pickPreferredContactValue(existing.nickname, incoming.nickname, { preferIncomingWhenLonger: true }),
            name: pickPreferredContactValue(existing.name, incoming.name, { preferIncomingWhenLonger: true }),
            gender: (existing.gender && existing.gender !== 'X') ? existing.gender : (incoming.gender || existing.gender || 'X'),
            account: (!isAutoGeneratedAccount(existing.account) && String(existing.account || '').trim())
                ? existing.account
                : pickPreferredContactValue(existing.account, incoming.account),
            language: pickPreferredContactValue(existing.language, incoming.language),
            signature: pickPreferredContactValue(existing.signature, incoming.signature, { preferIncomingWhenLonger: true }),
            lore: pickPreferredContactValue(existing.lore, incoming.lore, { preferIncomingWhenLonger: true }),
            presetAssoc: (existing.presetAssoc && existing.presetAssoc !== 'NONE') ? existing.presetAssoc : (incoming.presetAssoc || 'NONE'),
            worldbookAssoc: mergeWorldbookAssocValues(existing.worldbookAssoc, incoming.worldbookAssoc),
            avatar: pickPreferredContactValue(existing.avatar, incoming.avatar)
        };
        const changes = {};
        Object.keys(next).forEach((key) => {
            const currentText = String(existing[key] == null ? '' : existing[key]).trim();
            const nextText = String(next[key] == null ? '' : next[key]).trim();
            if (currentText !== nextText) changes[key] = next[key];
        });
        return changes;
    }

    async function findDuplicateContact(contactData, excludeId = null) {
        const fingerprint = buildContactDuplicateFingerprint(contactData);
        if (!fingerprint) return null;
        const contacts = await db.contacts.toArray();
        return contacts.find((contact) => {
            if (!contact || contact.id === excludeId) return false;
            return buildContactDuplicateFingerprint(contact) === fingerprint;
        }) || null;
    }

    function buildRelationFingerprint(relation) {
        if (!relation) return '';
        const source = String(relation.sourceGlobalId || '').trim();
        const target = String(relation.targetGlobalId || '').trim();
        if (!source || !target) return '';
        const relationType = normalizeContactIdentityText(relation.relationType);
        const relationDesc = normalizeContactIdentityText(relation.relationDesc);
        return [source, target, relationType, relationDesc].join('|');
    }

    async function restoreImportedRelations(importedRelations, oldGlobalId, newGlobalId) {
        if (!Array.isArray(importedRelations) || !importedRelations.length || !newGlobalId) return;
        const existingRelations = await db.relations.toArray();
        const seen = new Set(existingRelations.map((relation) => buildRelationFingerprint(relation)).filter(Boolean));
        for (const rawRelation of importedRelations) {
            if (!rawRelation || typeof rawRelation !== 'object') continue;
            const relation = { ...rawRelation };
            delete relation.id;
            if (oldGlobalId && relation.sourceGlobalId === oldGlobalId) relation.sourceGlobalId = newGlobalId;
            if (oldGlobalId && relation.targetGlobalId === oldGlobalId) relation.targetGlobalId = newGlobalId;
            const key = buildRelationFingerprint(relation);
            if (!key || seen.has(key)) continue;
            await db.relations.add(relation);
            seen.add(key);
        }
    }

    function getPrimaryContactActionButton() {
        return document.querySelector('#view-editor .action-group > .btn-primary');
    }

    function setPrimaryContactActionPending(pending, idleLabel = 'SAVE CONTACT', busyLabel = 'SAVING...') {
        const button = getPrimaryContactActionButton();
        if (!button) return;
        button.disabled = !!pending;
        button.style.pointerEvents = pending ? 'none' : '';
        button.style.opacity = pending ? '0.6' : '';
        button.textContent = pending ? busyLabel : idleLabel;
    }

    // ================= 视图与 Dock 控制 =================
    function switchMainView(viewId, dockEl) {
        document.querySelectorAll('.view-container').forEach(v => v.classList.remove('active'));
        document.getElementById(viewId).classList.add('active');
        
        document.querySelectorAll('.dock-item').forEach(d => d.classList.remove('active'));
        if(dockEl) dockEl.classList.add('active');
    }

    function switchListTab(type) {
        currentListType = type;
        switchMainView('view-list', document.querySelectorAll('.dock-item')[type === 'CHAR' ? 0 : 1]);
        loadList();
    }

    // ================= 弹窗控制 =================
    function openOptionsModal() { document.getElementById('options-modal').classList.add('show'); }
    function closeOptionsModal() { document.getElementById('options-modal').classList.remove('show'); }
    document.getElementById('options-modal').addEventListener('click', closeOptionsModal);
    
    function closeRelationModal() {
        closeAllDropdowns();
        document.getElementById('relation-modal').classList.remove('show');
    }
    document.getElementById('relation-modal').addEventListener('click', closeRelationModal);

    // ================= 数据列表加载 (联系人) =================
    async function loadList() {
        const contacts = await db.contacts.where('type').equals(currentListType).toArray();
        const container = document.getElementById('contact-list-container');
        container.innerHTML = '';

        if (contacts.length === 0) {
            container.innerHTML = `<div style="text-align:center; padding-top: 50px; font-size: 11px; color: #aaa; font-weight: 800; text-transform: uppercase;">No ${currentListType} contacts. Click + to add.</div>`;
            return;
        }

        contacts.forEach(contact => {
            const avatarStyle = contact.avatar ? `style="background-image: url('${contact.avatar}')"` : '';
            container.innerHTML += `
                <div class="contact-item" onclick="openEditor(${contact.id})">
                    <div class="contact-avatar" ${avatarStyle}></div>
                    <div class="contact-info">
                        <div class="contact-top">
                            <span class="contact-name">${contact.nickname || 'Unknown'}</span>
                        </div>
                        <div class="contact-account">@${contact.account || 'null'}</div>
                        <div class="contact-desc">${contact.signature || contact.lore || 'No description...'}</div>
                    </div>
                </div>
            `;
        });
    }

    // ================= 关系网核心逻辑 =================
    
    // 获取所有可用实体 (USER, CHAR, NPC)
    async function getAllNetworkEntities() {
        let entities = [];
        try {
            const users = await masksDb.masks.where('type').equals('USER').toArray();
            users.forEach(u => entities.push({ globalId: 'USER_' + u.id, name: u.nickname, type: 'USER', avatar: u.avatar }));
        } catch(e) { console.warn("MasksDB missing or empty."); }
        
        const contacts = await db.contacts.toArray();
        contacts.forEach(c => entities.push({ globalId: c.type + '_' + c.id, name: c.nickname, type: c.type, avatar: c.avatar }));
        
        return entities;
    }

    // 载入关系网总列表
    async function loadNetworkMainList() {
        const container = document.getElementById('network-main-list');
        container.innerHTML = '';
        const contacts = await db.contacts.toArray(); 
        
        if (contacts.length === 0) {
            container.innerHTML = `<div style="text-align:center; padding-top: 50px; font-size: 11px; color: #aaa; font-weight: 800; text-transform: uppercase;">No contacts available.</div>`;
            return;
        }

        contacts.forEach(contact => {
            const avatarStyle = contact.avatar ? `style="background-image: url('${contact.avatar}')"` : '';
            container.innerHTML += `
                <div class="contact-item" onclick="openNetworkDetail('${contact.id}', '${contact.type}', '${contact.nickname || 'Unknown'}')">
                    <div class="contact-avatar" ${avatarStyle}></div>
                    <div class="contact-info">
                        <div class="contact-top">
                            <span class="contact-name">${contact.nickname || 'Unknown'}</span>
                            <span style="font-size: 9px; font-weight: 800; padding: 3px 6px; background: var(--accent-dark); color: #fff; border-radius: 4px; letter-spacing: 1px;">${contact.type}</span>
                        </div>
                        <div class="contact-desc">Click to manage relations...</div>
                    </div>
                </div>
            `;
        });
    }

    // 打开单个实体的关系详情
    function openNetworkDetail(id, type, name) {
        currentNetworkEntity = { globalId: type + '_' + id, name, type };
        document.getElementById('network-detail-title').textContent = `${name} - RELATIONS`;
        
        document.getElementById('view-network').classList.remove('active');
        document.getElementById('view-network-detail').classList.add('active');
        document.getElementById('dock-bar').style.display = 'none'; // 隐藏Dock
        
        loadRelations();
    }

    function closeNetworkDetail() {
        document.getElementById('view-network-detail').classList.remove('active');
        document.getElementById('view-network').classList.add('active');
        document.getElementById('dock-bar').style.display = 'flex'; // 恢复Dock
    }

    // 载入具体关系数据 (双向同步体现：查询作为 source 或 target 的记录)
    async function loadRelations() {
        if(!currentNetworkEntity) return;
        const container = document.getElementById('network-relation-list');
        container.innerHTML = '';
        
        const allRels = await db.relations.toArray();
        const myRels = allRels.filter(r => r.sourceGlobalId === currentNetworkEntity.globalId || r.targetGlobalId === currentNetworkEntity.globalId);
        
        if(myRels.length === 0) {
            container.innerHTML = `<div style="text-align:center; padding-top: 50px; font-size: 11px; color: #aaa; font-weight: 800; text-transform: uppercase;">No relations found. Click + to add.</div>`;
            return;
        }
        
        const allEntities = await getAllNetworkEntities();
        
        myRels.forEach(rel => {
            const isSource = rel.sourceGlobalId === currentNetworkEntity.globalId;
            const otherId = isSource ? rel.targetGlobalId : rel.sourceGlobalId;
            const otherEntity = allEntities.find(e => e.globalId === otherId);
            
            if(!otherEntity) return; 
            
            const avatarStyle = otherEntity.avatar ? `style="background-image: url('${otherEntity.avatar}')"` : '';
            const relTypeDisp = getRelationTypeDisplayLabel(rel.relationType || rel.relationDesc);
            const relDetailDisp = rel.relationType && rel.relationDesc ? rel.relationDesc : '';
            
            container.innerHTML += `
                <div class="contact-item" onclick="openRelationModal(${rel.id})" style="cursor: pointer;">
                    <div class="contact-avatar" ${avatarStyle}></div>
                    <div class="contact-info">
                        <div class="contact-top">
                            <span class="contact-name">${otherEntity.name}</span>
                            <span style="font-size: 9px; font-weight: 800; padding: 3px 6px; background: #e0e0e0; color: #333; border-radius: 4px; letter-spacing: 1px;">${otherEntity.type}</span>
                        </div>
                        <div class="contact-desc" style="font-weight: 800; color: var(--accent-dark); margin-top: 4px;">
                            [${relTypeDisp}] ${relDetailDisp}
                        </div>
                    </div>
                </div>
            `;
        });
    }

    // 打开添加/编辑关系弹窗
    async function openRelationModal(relId = null) {
        syncRelationTypeTabLabels();
        document.getElementById('inp-rel-edit-id').value = relId || '';
        const allEntities = await getAllNetworkEntities();

        if (relId) {
            // Edit mode
            document.getElementById('rel-edit-actions').style.display = 'flex';
            document.querySelector('#rel-target-group .input-wrap').style.pointerEvents = 'none'; // Lock target change

            const rel = await db.relations.get(parseInt(relId));
            const isSource = rel.sourceGlobalId === currentNetworkEntity.globalId;
            const otherId = isSource ? rel.targetGlobalId : rel.sourceGlobalId;
            const otherEntity = allEntities.find(e => e.globalId === otherId);

            document.getElementById('disp-rel-target').value = otherEntity ? `[${otherEntity.type}] ${otherEntity.name}` : otherId;
            document.getElementById('inp-rel-target').value = otherId;
            document.getElementById('inp-rel-target-name').value = otherEntity ? otherEntity.name : '';
            closeDropdownList(document.getElementById('rel-target-list'));

            const type = normalizeRelationType(rel.relationType) || 'CUSTOM';
            let matchedTab = false;
            document.querySelectorAll('#relation-modal .tab-btn').forEach(btn => {
                if(btn.textContent.trim() === type) {
                    setRelationType(type, btn);
                    matchedTab = true;
                }
            });
            if(!matchedTab) {
                setRelationType('CUSTOM', document.querySelectorAll('#relation-modal .tab-btn')[4]);
                document.getElementById('inp-rel-custom').value = type;
            }

            document.getElementById('inp-rel-desc').value = rel.relationDesc || '';

        } else {
            // Create mode
            document.getElementById('rel-edit-actions').style.display = 'none';
            document.querySelector('#rel-target-group .input-wrap').style.pointerEvents = 'auto';

            const availableTargets = allEntities.filter(e => e.globalId !== currentNetworkEntity.globalId);
            const listDiv = document.getElementById('rel-target-list');
            listDiv.innerHTML = '';
            
            if(availableTargets.length === 0) {
                listDiv.innerHTML = '<div class="dropdown-item" style="color:#aaa;">No targets available</div>';
            } else {
                availableTargets.forEach(target => {
                    listDiv.innerHTML += `<div class="dropdown-item" onclick="selectRelationTarget('${target.globalId}', '${target.name}', '${target.type}', event)">[${target.type}] ${target.name}</div>`;
                });
            }
            
            document.getElementById('disp-rel-target').value = '';
            document.getElementById('inp-rel-target').value = '';
            document.getElementById('inp-rel-target-name').value = '';
            setRelationType('家人', document.querySelectorAll('#relation-modal .tab-btn')[0]);
            document.getElementById('inp-rel-custom').value = '';
            document.getElementById('inp-rel-desc').value = '';
        }

        document.getElementById('relation-modal').classList.add('show');
    }

    function selectRelationTarget(globalId, name, type, event) {
        event.preventDefault();
        event.stopPropagation();
        if (typeof event.stopImmediatePropagation === 'function') event.stopImmediatePropagation();
        document.getElementById('disp-rel-target').value = `[${type}] ${name}`;
        document.getElementById('inp-rel-target').value = globalId;
        document.getElementById('inp-rel-target-name').value = name;
        closeDropdownList(document.getElementById('rel-target-list'));
    }

    function setRelationType(val, el) {
        const group = el.parentElement;
        group.querySelectorAll('.tab-btn').forEach(btn => btn.classList.remove('active'));
        el.classList.add('active');
        const normalizedValue = val === 'CUSTOM' ? 'CUSTOM' : normalizeRelationType(val);
        document.getElementById('inp-rel-type').value = normalizedValue;
        if (normalizedValue !== 'CUSTOM' && el.textContent.trim() !== normalizedValue) {
            el.textContent = normalizedValue;
        }
        
        if(normalizedValue === 'CUSTOM') {
            document.getElementById('custom-rel-group').style.display = 'flex';
        } else {
            document.getElementById('custom-rel-group').style.display = 'none';
        }
    }

    async function saveRelation() {
        const relEditId = document.getElementById('inp-rel-edit-id').value;
        const targetGlobalId = document.getElementById('inp-rel-target').value;
        let relType = document.getElementById('inp-rel-type').value;
        
        if(relType === 'CUSTOM') {
            relType = document.getElementById('inp-rel-custom').value.trim();
            if(!relType) return alert("Please specify the custom relation. (请填写自定义关系)");
        } else {
            relType = normalizeRelationType(relType);
        }
        
        if(!targetGlobalId) return alert("Please select a target entity. (请选择目标)");

        const relDesc = document.getElementById('inp-rel-desc').value.trim();
        if(!relDesc) return alert("Please describe the relation details. (请填写关系描述)");
        
        const relData = {
            sourceGlobalId: currentNetworkEntity.globalId,
            targetGlobalId: targetGlobalId,
            relationType: relType,
            relationDesc: relDesc
        };

        if (relEditId) {
            await db.relations.update(parseInt(relEditId), relData);
        } else {
            await db.relations.add(relData);
        }
        
        closeRelationModal();
        loadRelations();
    }

    async function deleteRelation() {
        const relEditId = document.getElementById('inp-rel-edit-id').value;
        if (!relEditId) return;
        if (confirm("Delete this relation? (确认删除此关系？)")) {
            await db.relations.delete(parseInt(relEditId));
            closeRelationModal();
            loadRelations();
        }
    }

    async function exportRelation() {
        const relEditId = document.getElementById('inp-rel-edit-id').value;
        if (!relEditId) return;
        const rel = await db.relations.get(parseInt(relEditId));
        const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(rel, null, 2));
        const dlAnchorElem = document.createElement('a');
        dlAnchorElem.setAttribute("href", dataStr);
        dlAnchorElem.setAttribute("download", `relation_${rel.id}.json`);
        dlAnchorElem.click();
    }


    // ================= 账号自动生成器 =================
    function generateUniqueAccount() {
        const prefix = currentListType === 'CHAR' ? 'C_' : 'N_';
        const timestamp = Date.now().toString(36).toUpperCase();
        const randomStr = Math.random().toString(36).substring(2, 6).toUpperCase();
        return prefix + timestamp + '_' + randomStr;
    }

    // ================= 下拉栏全局交互与立牌双向绑定逻辑 =================
    function resetDropdownFloatingStyles(list) {
        if (!list) return;
        list.style.display = 'none';
        list.style.position = '';
        list.style.left = '';
        list.style.right = '';
        list.style.top = '';
        list.style.bottom = '';
        list.style.width = '';
        list.style.marginTop = '';
        list.style.marginBottom = '';
        list.style.maxHeight = '';
        list.style.visibility = '';
        list.style.pointerEvents = '';
        list.style.transform = '';
        list.style.transformOrigin = '';
        list.style.zIndex = '';
    }

    function closeDropdownList(list) {
        if (!list) return;
        const wasOpen = list.style.display === 'flex' || list.parentNode === getDropdownLayer();
        restoreDropdownMount(list);
        resetDropdownFloatingStyles(list);
        list.dataset.direction = '';
        const wrap = getDropdownAnchor(list);
        if (wrap) wrap.classList.remove('is-open');
        if (activeDropdownList === list) activeDropdownList = null;
        if (wasOpen) lockDropdownToggle();
    }

    function closeAllDropdowns(exceptId = '') {
        document.querySelectorAll('.custom-dropdown').forEach(list => {
            if (exceptId && list.id === exceptId) return;
            closeDropdownList(list);
        });
    }

    function getDropdownLayer() {
        let layer = document.getElementById('contacts-dropdown-layer');
        if (!layer) {
            layer = document.createElement('div');
            layer.id = 'contacts-dropdown-layer';
            document.body.appendChild(layer);
        }
        layer.classList.add('contacts-floating-layer');
        layer.dataset.miniFloatingLayer = '1';
        return layer;
    }

    function getDropdownAnchor(list) {
        if (!list) return null;
        if (list.__miniDropdownAnchor && document.contains(list.__miniDropdownAnchor)) return list.__miniDropdownAnchor;
        const wrap = list.closest('.input-wrap');
        if (wrap) list.__miniDropdownAnchor = wrap;
        return wrap || null;
    }

    function getDropdownListByType(type) {
        const listId = type === 'language' ? 'lang-list' : `${type}-list`;
        return document.getElementById(listId);
    }

    function mountDropdownToLayer(list, wrap) {
        if (!list || !wrap) return;
        if (!list.__miniDropdownHome) {
            list.__miniDropdownHome = {
                parent: list.parentNode,
                nextSibling: list.nextSibling
            };
        }
        list.__miniDropdownAnchor = wrap;
        const layer = getDropdownLayer();
        if (list.parentNode !== layer) layer.appendChild(list);
    }

    function restoreDropdownMount(list) {
        if (!list || !list.__miniDropdownHome) return;
        const { parent, nextSibling } = list.__miniDropdownHome;
        if (!parent) return;
        if (nextSibling && nextSibling.parentNode === parent) parent.insertBefore(list, nextSibling);
        else parent.appendChild(list);
    }

    function positionDropdown(list) {
        if (!list) return;
        const wrap = getDropdownAnchor(list);
        if (!wrap) return;

        mountDropdownToLayer(list, wrap);

        const gap = 6;
        const rect = wrap.getBoundingClientRect();
        const viewportHeight = window.innerHeight || document.documentElement.clientHeight || 0;
        const naturalWidth = Math.max(1, wrap.offsetWidth || rect.width || 1);
        const scale = Math.max(0.01, rect.width / naturalWidth);

        list.style.display = 'flex';
        list.style.position = 'absolute';
        list.style.left = `${rect.left}px`;
        list.style.right = 'auto';
        list.style.top = '0';
        list.style.bottom = 'auto';
        list.style.width = `${naturalWidth}px`;
        list.style.marginTop = '0';
        list.style.marginBottom = '0';
        list.style.visibility = 'hidden';
        list.style.pointerEvents = 'none';
        list.style.transform = `scale(${scale})`;
        list.style.transformOrigin = 'left top';
        list.style.zIndex = '10021';

        const naturalHeight = Math.max(
            44,
            Math.ceil((list.scrollHeight || list.offsetHeight || 0) + 2)
        );
        const availableBelow = Math.max(96, Math.floor(viewportHeight - rect.bottom - gap));
        const availableAbove = Math.max(96, Math.floor(rect.top - gap));
        const displayHeight = naturalHeight * scale;
        const openUpward = displayHeight > availableBelow && availableAbove > availableBelow;
        const maxHeight = Math.max(96, Math.floor((openUpward ? availableAbove : availableBelow) / scale));

        list.dataset.direction = openUpward ? 'up' : 'down';
        list.style.top = openUpward ? 'auto' : `${rect.bottom + gap}px`;
        list.style.bottom = openUpward ? `${Math.max(0, viewportHeight - rect.top + gap)}px` : 'auto';
        list.style.maxHeight = `${maxHeight}px`;
        list.style.transformOrigin = openUpward ? 'left bottom' : 'left top';
        list.style.visibility = '';
        list.style.pointerEvents = 'auto';
        wrap.classList.add('is-open');
        activeDropdownList = list;
    }

    function toggleDropdown(listId) {
        if (isDropdownToggleLocked()) return;
        const list = document.getElementById(listId);
        if (!list) return;
        const shouldOpen = list.style.display !== 'flex';
        closeAllDropdowns(shouldOpen ? listId : '');
        if (!shouldOpen) return;
        positionDropdown(list);
    }

    function selectDropdownItem(type, value, label, event) {
        event.preventDefault();
        event.stopPropagation();
        if (typeof event.stopImmediatePropagation === 'function') event.stopImmediatePropagation();
        document.getElementById('disp-' + type).value = label;
        const hiddenInput = document.getElementById('inp-' + type);
        hiddenInput.value = value;
        closeDropdownList(getDropdownListByType(type));
        hiddenInput.dispatchEvent(new Event('input')); 
    }

    document.addEventListener('click', function(e) {
        if (!e.target.closest('.input-wrap') && !e.target.closest('.custom-dropdown')) {
            closeAllDropdowns();
        }
    });

    window.addEventListener('resize', () => {
        document.querySelectorAll('.custom-dropdown').forEach(list => {
            if (list.style.display === 'flex') positionDropdown(list);
        });
    });

    document.addEventListener('scroll', () => {
        document.querySelectorAll('.custom-dropdown').forEach(list => {
            if (list.style.display === 'flex') positionDropdown(list);
        });
    }, true);

    function bindInputToBadge(inputId, badgeId, fallback) {
        const inputEl = document.getElementById(inputId);
        const badgeEl = document.getElementById(badgeId);
        inputEl.addEventListener('input', () => {
            badgeEl.textContent = inputEl.value.trim() || fallback;
        });
    }
    
    function bindDropdownToBadge(inputId, badgeId, prefix) {
        const inputEl = document.getElementById(inputId);
        const badgeEl = document.getElementById(badgeId);
        const displayEl = document.getElementById(inputId.replace('inp-', 'disp-'));
        const render = () => {
            const displayValue = displayEl && displayEl.value ? displayEl.value.trim() : '';
            const fallbackValue = String(inputEl.value || '').trim();
            const resolved = displayValue || (fallbackValue && !/^none$/i.test(fallbackValue) ? fallbackValue : 'None');
            badgeEl.textContent = prefix + ": " + resolved;
        };
        inputEl.addEventListener('input', render);
        if (displayEl) displayEl.addEventListener('input', render);
    }

    function renderWorldbookSelectionTags(rawValue = null) {
        const container = document.getElementById('worldbook-selection-tags');
        if (!container) return;
        const values = parseWorldbookAssocValues(rawValue == null ? document.getElementById('inp-worldbook').value : rawValue);
        const optionsState = window.__miniContactAssocOptions || {};
        const options = Array.isArray(optionsState.worldbook) ? optionsState.worldbook : [];
        const labels = values
            .map((value) => {
                const match = options.find((item) => item && item.value === value);
                return match && match.label ? match.label : value.replace(/^worldbook:/i, 'Group ');
            })
            .filter(Boolean);
        if (!labels.length) {
            container.innerHTML = '';
            return;
        }
        container.innerHTML = labels.map((label) => `<span class="assoc-chip">${label}</span>`).join('');
    }

    bindInputToBadge('inp-nickname', 'badge-nickname', 'Name...');
    bindInputToBadge('inp-name', 'badge-name', 'Full Name');
    bindInputToBadge('inp-sign', 'badge-sign', 'Signature text...');
    bindInputToBadge('inp-lore', 'badge-lore', 'Detailed background story or lore will be displayed here...');
    bindInputToBadge('inp-language', 'badge-language', '中文 (Mandarin)'); 
    bindDropdownToBadge('inp-preset', 'badge-preset', 'P');
    bindDropdownToBadge('inp-worldbook', 'badge-worldbook', 'W');
    document.getElementById('inp-worldbook').addEventListener('input', () => renderWorldbookSelectionTags());

    function setGender(val, el) {
        document.querySelectorAll('.tab-btn').forEach(btn => btn.classList.remove('active'));
        el.classList.add('active');
        document.getElementById('inp-gender').value = val;
        
        let displayGender = 'Secret';
        if(val === 'M') displayGender = 'Male';
        if(val === 'F') displayGender = 'Female';
        document.getElementById('badge-gender').textContent = displayGender;
    }

    document.getElementById('inp-avatar').addEventListener('change', function(e) {
        const file = e.target.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function(event) {
                const b64 = event.target.result;
                document.getElementById('val-avatar').value = b64;
                document.getElementById('badge-avatar').style.backgroundImage = `url(${b64})`;
            };
            reader.readAsDataURL(file);
        }
    });

    // ================= 编辑器控制 =================
    function resetForm() {
        currentEditId = null;
        contactSavePending = false;
        setPrimaryContactActionPending(false);
        document.getElementById('editor-title').textContent = `NEW ${currentListType}`;
        document.getElementById('edit-actions').style.display = 'none';
        
        document.getElementById('inp-nickname').value = '';
        document.getElementById('inp-name').value = '';
        document.getElementById('inp-sign').value = '';
        document.getElementById('inp-lore').value = '';
        document.getElementById('val-avatar').value = '';
        setGender('M', document.querySelectorAll('.tab-btn')[0]);

        document.getElementById('inp-language').value = '中文 (Mandarin)';
        document.getElementById('disp-language').value = '中文 (Mandarin)';
        
        document.getElementById('inp-preset').value = 'NONE';
        document.getElementById('disp-preset').value = 'None';
        
        document.getElementById('inp-worldbook').value = 'NONE';
        document.getElementById('disp-worldbook').value = 'None';

        autoGeneratedAccount = generateUniqueAccount();
        document.getElementById('badge-account').textContent = autoGeneratedAccount;

        ['inp-nickname', 'inp-name', 'inp-sign', 'inp-lore', 'inp-language', 'inp-preset', 'inp-worldbook'].forEach(id => {
            document.getElementById(id).dispatchEvent(new Event('input'));
        });
        document.getElementById('badge-avatar').style.backgroundImage = 'none';
    }

    async function openEditor(id = null) {
        document.getElementById('view-list').classList.remove('active');
        document.getElementById('view-network').classList.remove('active');
        document.getElementById('view-editor').classList.add('active');
        document.getElementById('dock-bar').style.display = 'none';
        
        resetForm();

        if (id) {
            currentEditId = id;
            document.getElementById('editor-title').textContent = `EDIT ${currentListType}`;
            document.getElementById('edit-actions').style.display = 'flex';
            
            const contact = await db.contacts.get(id);
            if (contact) {
                autoGeneratedAccount = contact.account;
                document.getElementById('badge-account').textContent = autoGeneratedAccount;
                
                document.getElementById('inp-nickname').value = contact.nickname || '';
                document.getElementById('inp-name').value = contact.name || '';
                document.getElementById('inp-sign').value = contact.signature || '';
                document.getElementById('inp-lore').value = contact.lore || '';
                document.getElementById('val-avatar').value = contact.avatar || '';
                
                const lang = contact.language || '中文 (Mandarin)';
                document.getElementById('inp-language').value = lang;
                document.getElementById('disp-language').value = lang;

                const preset = contact.presetAssoc || 'NONE';
                document.getElementById('inp-preset').value = preset;
                document.getElementById('disp-preset').value = resolveContactAssocLabel('preset', preset);

                const wb = contact.worldbookAssoc || 'NONE';
                document.getElementById('inp-worldbook').value = wb;
                document.getElementById('disp-worldbook').value = resolveContactAssocLabel('worldbook', wb);

                const tabs = document.querySelectorAll('.tab-btn');
                if(contact.gender === 'M') setGender('M', tabs[0]);
                else if(contact.gender === 'F') setGender('F', tabs[1]);
                else setGender('X', tabs[2]);

                ['inp-nickname', 'inp-name', 'inp-sign', 'inp-lore', 'inp-language', 'inp-preset', 'inp-worldbook'].forEach(id => {
                    document.getElementById(id).dispatchEvent(new Event('input'));
                });
                
                if(contact.avatar) {
                    document.getElementById('badge-avatar').style.backgroundImage = `url('${contact.avatar}')`;
                }
            }
        }
    }

    function closeEditor() {
        contactSavePending = false;
        setPrimaryContactActionPending(false);
        closeAllDropdowns();
        document.getElementById('view-editor').classList.remove('active');
        document.getElementById('view-list').classList.add('active');
        document.getElementById('dock-bar').style.display = 'flex'; 
        loadList();
    }

    async function maybeGenerateContactPersona(contactId, options = {}) {
        if (contactId == null || typeof window.ensureWechatContactPersonaProfile !== 'function') return;
        try {
            await window.ensureWechatContactPersonaProfile(contactId, options);
        } catch (error) {
            console.error('Failed to generate contact persona profile:', error);
        }
    }

    async function saveContact() {
        if (contactSavePending) return;
        const contactData = collectCurrentContactFormData();

        if(!contactData.nickname) return alert("Nickname is required. (昵称为必填项)");

        contactSavePending = true;
        setPrimaryContactActionPending(true);
        try {
            let savedContactId = null;
            const duplicate = await findDuplicateContact(contactData, currentEditId);
            if (duplicate && currentEditId && duplicate.id !== currentEditId) {
                alert("检测到重复联系人，请直接编辑现有条目。");
                return;
            }

            if (duplicate && !currentEditId) {
                const changes = buildMergedContactChanges(duplicate, contactData);
                if (Object.keys(changes).length) {
                    await db.contacts.update(duplicate.id, changes);
                }
                savedContactId = duplicate.id;
                alert("检测到重复联系人，已自动合并到现有条目。");
            } else if (currentEditId) {
                await db.contacts.update(currentEditId, contactData);
                savedContactId = currentEditId;
            } else {
                savedContactId = await db.contacts.add(contactData);
            }
            closeEditor();
            void maybeGenerateContactPersona(savedContactId, { force: true, silent: true });
        } finally {
            contactSavePending = false;
            setPrimaryContactActionPending(false);
        }
    }

    async function deleteContact() {
        if (!currentEditId) return;
        if(confirm("Delete this contact? (删除不可逆转)")) {
            await db.contacts.delete(currentEditId);
            closeEditor();
        }
    }

    // ================= 导入导出功能 =================
    async function importData(event) {
        if (contactImportPending) return;
        const file = event.target.files[0];
        if (!file) return;
        contactImportPending = true;

        try {
            let contactData = null;
            let avatarBase64 = null;

            if (file.name.toLowerCase().endsWith('.json')) {
                const text = await file.text();
                contactData = JSON.parse(text);
            } 
            else if (file.name.toLowerCase().endsWith('.png')) {
                avatarBase64 = await new Promise((res) => {
                    const r = new FileReader();
                    r.onload = (e) => res(e.target.result);
                    r.readAsDataURL(file);
                });
                if (!window.MiniPngCard || typeof window.MiniPngCard.readFile !== 'function') {
                    throw new Error("PNG import helper is not available.");
                }
                const embeddedPayload = await window.MiniPngCard.readFile(file);
                if (embeddedPayload.mini && embeddedPayload.mini.app === 'mini' && embeddedPayload.mini.data) {
                    contactData = buildImportedContactFromCharacterData(embeddedPayload.mini.data, avatarBase64);
                    if (embeddedPayload.mini.format === 'contact' && Array.isArray(embeddedPayload.mini.data.relations)) {
                        contactData.relations = embeddedPayload.mini.data.relations;
                    }
                } else if (embeddedPayload.chara) {
                    contactData = buildImportedContactFromCharacterData(embeddedPayload.chara.data || embeddedPayload.chara, avatarBase64);
                } else {
                    throw new Error("No embedded character data found in PNG.");
                }
            }

            if (contactData && contactData.nickname) {
                const importedRelations = contactData.relations;
                const originalId = contactData.id;
                const originalType = contactData.type || currentListType;

                delete contactData.id; 
                delete contactData.relations;
                contactData.type = currentListType; 
                if(!contactData.account) contactData.account = generateUniqueAccount();
                if(!contactData.avatar && avatarBase64) contactData.avatar = avatarBase64;
                if(!contactData.language) contactData.language = '中文 (Mandarin)';

                const duplicate = await findDuplicateContact(contactData);
                let targetId = null;
                let merged = false;

                if (duplicate) {
                    const changes = buildMergedContactChanges(duplicate, contactData);
                    if (Object.keys(changes).length) {
                        await db.contacts.update(duplicate.id, changes);
                    }
                    targetId = duplicate.id;
                    merged = true;
                } else {
                    targetId = await db.contacts.add(contactData);
                }

                const newGlobalId = currentListType + '_' + targetId;
                const oldGlobalId = originalId != null ? `${originalType}_${originalId}` : '';
                await restoreImportedRelations(importedRelations, oldGlobalId, newGlobalId);

                loadList();
                void maybeGenerateContactPersona(targetId, { force: true, silent: true });
                alert(merged ? '检测到重复联系人，已导入并合并到现有条目。' : '导入成功 (Import successful)');
            } else {
                throw new Error("Format not recognized.");
            }
        } catch(err) {
            console.error(err);
            alert('导入失败 (Import failed): ' + err.message);
        } finally {
            contactImportPending = false;
            event.target.value = '';
        }
    }

    async function exportJSON() {
        if (!currentEditId) return;
        const contact = await db.contacts.get(currentEditId);
        
        // Attach associated relations for proper network export
        const globalId = contact.type + '_' + contact.id;
        const allRels = await db.relations.toArray();
        contact.relations = allRels.filter(r => r.sourceGlobalId === globalId || r.targetGlobalId === globalId);

        const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(contact, null, 2));
        const dlAnchorElem = document.createElement('a');
        dlAnchorElem.setAttribute("href", dataStr);
        dlAnchorElem.setAttribute("download", `contact_${contact.account}.json`);
        dlAnchorElem.click();
    }

    async function exportPNG() {
        const standee = document.querySelector('#capture-area .acrylic-standee');
        if (!standee) return;
        const exportData = await buildExportableContactData();
        const canvas = await html2canvas(standee, {
            scale: 3,
            backgroundColor: null,
            useCORS: true
        });
        let href = canvas.toDataURL('image/png');
        if (window.MiniPngCard && typeof window.MiniPngCard.embedDataUrl === 'function') {
            href = window.MiniPngCard.embedDataUrl(href, [
                { keyword: 'mini', value: { app: 'mini', format: 'contact', data: exportData } },
                { keyword: 'chara', value: window.MiniPngCard.buildTavernCard(exportData) }
            ]);
        }
        const link = document.createElement('a');
        link.download = `contact_${autoGeneratedAccount}_standee.png`;
        link.href = href;
        link.click();
    }

    // ================= 初始化 =================
    function syncContactsNavTitles() {
        const contactsTitle = document.querySelector('#view-list .nav-title');
        if (contactsTitle) contactsTitle.textContent = 'CONTACTS';
        const networkTitle = document.querySelector('#view-network .nav-title');
        if (networkTitle) networkTitle.textContent = 'NETWORK';
    }

    document.addEventListener('DOMContentLoaded', () => {
        syncContactsNavTitles();
        syncRelationTypeTabLabels();
        loadList(); 
    });

(function () {
  const route = "contacts";
  const placeholderUrl = "../assets/初始占位图.png";
  const placeholderSelectors = [".contact-avatar","#badge-avatar"];
  const bindings = [];
  const backSelectors = [];
  const overrideFunctions = ["returnToParent"];
  const shell = window.parent && window.parent.__miniShell;

  function openRoute(target) {
    if (shell && typeof shell.open === 'function') shell.open(target, route);
  }

  function goBack() {
    if (shell && typeof shell.back === 'function') shell.back(route);
  }

  function patchHistoryBack() {
    try {
      if (window.history) window.history.back = goBack;
      if (window.History && window.History.prototype) window.History.prototype.back = goBack;
    } catch (error) {}
  }

  function replaceWithPlaceholder(el) {
    if (!el) return;
    const inlineBg = (el.style.backgroundImage || '').trim();
    const computedBg = (window.getComputedStyle(el).backgroundImage || '').trim();
    const currentBg = inlineBg && inlineBg !== 'none' ? inlineBg : computedBg;
    const needsPlaceholder = !currentBg || currentBg === 'none' || currentBg.includes('data:image/svg+xml') || currentBg === 'url("")' || currentBg === 'url()';
    if (!needsPlaceholder) return;
    el.style.backgroundImage = 'url(' + placeholderUrl + ')';
    el.style.backgroundSize = 'cover';
    el.style.backgroundPosition = 'center';
    el.style.backgroundRepeat = 'no-repeat';
  }

  function applyPlaceholders(root = document) {
    placeholderSelectors.forEach((selector) => {
      root.querySelectorAll(selector).forEach(replaceWithPlaceholder);
    });
  }

  function watchPlaceholders() {
    if (!placeholderSelectors.length) return;
    const observer = new MutationObserver(() => applyPlaceholders());
    observer.observe(document.documentElement, {
      subtree: true,
      childList: true,
      attributes: true,
      attributeFilter: ['style', 'class']
    });
  }

  function bindAction(selector, binding) {
    document.querySelectorAll(selector).forEach((el) => {
      if (el.dataset.miniRouteBound === '1') return;
      el.dataset.miniRouteBound = '1';
      el.style.cursor = 'pointer';
      el.addEventListener('click', (event) => {
        event.preventDefault();
        event.stopImmediatePropagation();
        if (binding.action === 'back') {
          goBack();
        } else if (binding.action === 'open' && binding.target) {
          openRoute(binding.target);
        }
      }, true);
    });
  }

  function init() {
    patchHistoryBack();
    overrideFunctions.forEach((name) => {
      try {
        window[name] = goBack;
      } catch (error) {}
    });

    document.addEventListener('click', (event) => {
      const backTrigger = event.target.closest('[onclick*="history.back"]');
      if (!backTrigger) return;
      event.preventDefault();
      event.stopImmediatePropagation();
      goBack();
    }, true);

    applyPlaceholders();
    watchPlaceholders();

    backSelectors.forEach((selector) => bindAction(selector, { action: 'back' }));
    bindings.forEach((binding) => bindAction(binding.selector, binding));
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init, { once: true });
  } else {
    init();
  }
})();
